### ISSUE TITLE
display has changed 

### ISSUE THREAD

**Issue by geryan** [acefa-hubs/acefa-hubs.github.io#10]
Image is now full width, icons not displaying

![image](https://github.com/acefa-hubs/acefa-hubs.github.io/assets/4963182/5d18416f-0256-4f6d-a01f-714a0b84540b)

![image](https://github.com/acefa-hubs/acefa-hubs.github.io/assets/4963182/3070b537-412d-4459-a425-628fe9cb8d80)

**Comment by smwindecker** [comment]
this issue I believe has to do with the github action I set up that is supposed to rebuild the site when new work is pushed or a PR merged. It is obviously not working correctly, the site builds properly when I use `quarto publish gh-pages` from the clone of the acefa-hubs repo. 

tldr: github action not working

**Comment by smwindecker** [comment]
might have to do with the facts that the forks do not automatically fork the gh-pages branch as well
